library(dplyr)
library(tidyr)
setwd(".//coursera//getdata-projectfiles-UCI HAR Dataset//UCI HAR Dataset//")
train<-read.table(".//coursera//getdata-projectfiles-UCI HAR Dataset//UCI HAR Dataset//train//X_train.txt")
trainlabel<-read.table(".//coursera//getdata-projectfiles-UCI HAR Dataset//UCI HAR Dataset//train//y_train.txt")
test<-read.table(".//coursera//getdata-projectfiles-UCI HAR Dataset//UCI HAR Dataset//test//X_test.txt")
testlabel<-read.table(".//coursera//getdata-projectfiles-UCI HAR Dataset//UCI HAR Dataset//test//y_test.txt")
testsubject<-read.table("test//subject_test.txt")
trainsubject<-read.table("train//subject_train.txt")
trainset<-cbind(trainlabel,train)
testset<-cbind(testlabel,test)
rm(train)
rm(test)
rm(trainlabel)
rm(testlabel)
testset<-cbind(testsubject,testset)
trainset<-cbind(trainsubject,trainset)
rm(testsubject)
rm(trainsubject)
